[package]
name = "duplicate-checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2"
img_hash = "1.0"
gitignore = "1.0.7"